name: Automatic tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Move to ${{ github.workspace }}
        run: |
          cd ${{ github.workspace }}
      - name: Add url and token to config file 
        run: |
          sed -i 's#endpoint#${{ secrets.URL }}#g' src/UnitTests/logzio.config
          sed -i 's/token/${{ secrets.TOKEN }}/g' src/UnitTests/logzio.config
      - name: Run unit tests
        run: |
          dotnet test src --collect:"XPlat Code Coverage"
      - name: Print coverage results
        run: |
          find -path src/UnitTests/TestResults -type f -name coverage.cobertura.xml -print