name: Automatic tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Run unit tests
        run: dotnet test ${{ github.workspace }}/src/UnitTests/UnitTests.csproj