name: Automatic tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Add url and token to config file 
        run: |
          sed -i 's#endpoint#${{ secrets.URL }}#g' src/UnitTests/logzio.config
          sed -i 's/token/${{ secrets.TOKEN }}/g' src/UnitTests/logzio.config
      - name: Run unit tests
        run: |
          dotnet test src --collect:"XPlat Code Coverage"
      - name: Code-coverage
        run: |
          # Get one of the firectories in TestResults directory and move to it
          dir=$(ls -d src/UnitTests/TestResults/* | head -1)
          cd $dir

          # Get line-rate and branch-rate
          line_rate=$(head -2 *.xml | tail -1 | egrep -o "[0-1]\.?[0-9]*" | head -1)
          branch_rate=$(head -2 *.xml | tail -1 | egrep -o "[0-1]\.?[0-9]*" | head -2 | tail -1)

          # Print line-rate and branch-rate
          echo | awk -v num=$line_rate '{ printf "line-rate: %d%\n", (num * 100) }'
          echo | awk -v num=$branch_rate '{ printf "branch-rate: %d%\n", (num * 100) }'

          # Check code-coverage conditions
          echo | awk -v num=$line_rate '{ if (num < 0.5) { printf "line-rate is less than 50%"; exit 1 } else { exit 0 }}'
          exit_code=$?

          if [ $exit_code -eq 1 ]; then
            exit 1
          fi

          echo | awk -v num=$branch_rate '{ if (num < 0.35) { printf "line-rate is less than 30%"; exit 1 } else { exit 0 }}'
          exit_code=$?

          if [ $exit_code -eq 1 ]; then
            exit 1
          fi
      - name: Publish NuGet package
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_NAME: src/Core/Core.csproj
          NUGET_KEY: ${{ secrets.NUGET_KEY }}