name: Automatic tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Add url and token to config file 
        run: |
          sed -i 's/endpoint/${{ secrets.URL }}/g' ${{ github.workspace }}/src/UnitTests/logzio.config
          sed -i 's/token/${{ secrets.TOKEN }}/g' ${{ github.workspace }}/src/UnitTests/logzio.config
      - name: Run unit tests
        run: dotnet test ${{ github.workspace }}/src/UnitTests/UnitTests.csproj